# Generated by Django 6.0 on 2025-12-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('option1', models.CharField(max_length=200, verbose_name='گزینه ۱')),
                ('option2', models.CharField(max_length=200, verbose_name='گزینه ۲')),
                ('option3', models.CharField(max_length=200, verbose_name='گزینه ۳')),
                ('option4', models.CharField(max_length=200, verbose_name='گزینه ۴')),
                ('correct_answer', models.IntegerField(verbose_name='شماره گزینه صحیح')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20, unique=True, verbose_name='شماره دانشجویی')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='نمره نهایی')),
                ('date_taken', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آزمون')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='دانشجو')),
            ],
        ),
    ]
