# Generated by Django 6.0.2 on 2026-02-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='learning_content_files/'),
        ),
    ]
